grid_map_filters:
  - name: mean_in_radius_pre_digging
    type: gridMapFilters/MeanInRadiusFilter
    params:
      input_layer: pre_digging
      output_layer: pre_digging_smooth
      radius: 0.3
  - name: mean_in_radius_post
    type: gridMapFilters/MeanInRadiusFilter
    params:
      input_layer: post_digging
      output_layer: post_digging_smooth
      radius: 0.3
